### ISSUE TITLE
AttributeError: 'DatadogHandler' object has no attribute 'level'

### ISSUE THREAD

**Issue by r4881t** [hantswilliams/fastapi-datadog#1]
Based on your code, I created this class

```python
import logging
import sys
import os
import json

from datadog_api_client import ApiClient, Configuration
from datadog_api_client.v2.api.logs_api import LogsApi
from datadog_api_client.v2.model.content_encoding import ContentEncoding
from datadog_api_client.v2.model.http_log import HTTPLog
from datadog_api_client.v2.model.http_log_item import HTTPLogItem


# Read environment variable
log_level = os.getenv("LOG_LEVEL", "WARNING").upper()
print(f"Log level: {log_level}")

# Set up logging configuration
numeric_level = getattr(logging, log_level, None)
if not isinstance(numeric_level, int):
  print(f"Invalid log level: {log_level}")
  numeric_level = logging.INFO

# Set up logging to terminal
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s [%(process)d] [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)

# Define a custom logging handler that sends logs to Datadog
class DatadogHandler(logging.Handler):
    def __init__(self):
        # Set up the Datadog API client
        config = Configuration()
        if os.getenv("DD_API_KEY") is None:
            raise ValueError("DD_API_KEY environment variable is not set")
        config.api_key['DD-API-KEY'] = os.getenv("DD_API_KEY")
        config.host = 'https://http-intake.logs.datadoghq.com'
        api_client = ApiClient(configuration=config)
        self.logs = LogsApi(api_client)

    def emit(self, record):
        # # Ignore debug messages
        # if record.levelno == logging.DEBUG:
        #     return

        toJson = json.dumps(
            {
                "python-logging": {
                    "py-env": os.getenv("DD_LOGGING_ENV"),
                    "py-message": record.getMessage(),
                    "py-status": record.levelname.lower(),
                    "py-logger": record.name,
                    "py-stacktrace": record.exc_info,
                    "py-exception": record.exc_text,
                    "py-line": record.lineno,
                    "py-file": record.filename,
                    "py-function": record.funcName,
                    "py-level": record.levelno,
                    "py-path": record.pathname,
                    "py-thread": record.thread,
                    "py-threadName": record.threadName,
                    "py-process": record.process,
                    "py-processName": record.processName,
                    "py-args": record.args,
                    "py-msecs": record.msecs,
                    "py-relativeCreated": record.relativeCreated,
                    "py-created": record.created,
                    "py-module": record.module,
                }
            }

        )

        # Send the log to Datadog using the Logs API
        try:
            body = HTTPLog(
                [
                    HTTPLogItem(
                        ddsource="Python",
                        ddtags="env:{}".format(os.getenv("DD_LOGGING_ENV")),
                        hostname="{}".format(os.getenv("DD_HOSTNAME")),
                        message= toJson,
                        service="{}".format(os.getenv("DD_SERVICE")),
                        status=record.levelname.lower()
                    ),
                ]
            )

            self.logs.submit_log(
                content_encoding=ContentEncoding.DEFLATE,
                body=body)

        except Exception as e:
            print(f"Error sending log to Datadog: {e}")


def get_logger(name:str):
    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    try:
      logger.addHandler(DatadogHandler())
      logger.info(f"DatadogHandler added to logger {name}")
    except Exception as e:
      logger.warn(f"Error adding DatadogHandler to logger: {e}")
      logger.exception(e)
    return logger

```

When I run, I get error message

```shell

Log level: DEBUG
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/pranavprakash/workspace/friday/airflow/dags/friday/libs/dd_logging.py", line 105, in get_logger
    logger.info(f"DatadogHandler added to logger {name}")
  File "/Users/pranavprakash/anaconda3/lib/python3.11/logging/__init__.py", line 1489, in info
    self._log(INFO, msg, args, **kwargs)
  File "/Users/pranavprakash/anaconda3/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/Users/pranavprakash/anaconda3/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/Users/pranavprakash/anaconda3/lib/python3.11/logging/__init__.py", line 1705, in callHandlers
    if record.levelno >= hdlr.level:
                         ^^^^^^^^^^
AttributeError: 'DatadogHandler' object has no attribute 'level'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pranavprakash/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/pranavprakash/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pranavprakash/workspace/friday/venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/pranavprakash/workspace/friday/venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pranavprakash/anaconda3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/pranavprakash/anaconda3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pranavprakash/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/pranavprakash/workspace/friday/venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/Users/pranavprakash/workspace/friday/venv/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pranavprakash/workspace/friday/venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pranavprakash/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pranavprakash/workspace/friday/airflow/dags/friday/server.py", line 64, in <module>
    logger = get_logger(__name__)
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pranavprakash/workspace/friday/airflow/dags/friday/libs/dd_logging.py", line 107, in get_logger
    logger.warn(f"Error adding DatadogHandler to logger: {e}")
  File "/Users/pranavprakash/anaconda3/lib/python3.11/logging/__init__.py", line 1506, in warn
    self.warning(msg, *args, **kwargs)
  File "/Users/pranavprakash/anaconda3/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/Users/pranavprakash/anaconda3/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/Users/pranavprakash/anaconda3/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/Users/pranavprakash/anaconda3/lib/python3.11/logging/__init__.py", line 1705, in callHandlers
    if record.levelno >= hdlr.level:
                         ^^^^^^^^^^
AttributeError: 'DatadogHandler' object has no attribute 'level'
```

**Comment by r4881t** [comment]
Okay, I got the issue. I wasn't doing the ` super().__init__()` in DatadogHandler's __init__

the correct class is as follows

```python

class DatadogHandler(logging.Handler):
    def __init__(self):
        super().__init__()
        # Set up the Datadog API client
        config = Configuration()
        if os.getenv("DD_API_KEY") is None:
            raise ValueError("DD_API_KEY environment variable is not set")
        config.api_key['DD-API-KEY'] = os.getenv("DD_API_KEY")
        config.host = 'https://http-intake.logs.datadoghq.com'
        api_client = ApiClient(configuration=config)
        self.logs = LogsApi(api_client)

...
```
